spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.17.0.1/myblog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useAffectedRows=true
      username: root
      password: root
      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: true
  redis:
     host: 172.17.0.1
     port: 6379
     jedis:
        pool:
           max-active: -1
           max-wait: 3000ms
     timeout: 3000ms
  kafka:
    bootstrap-servers:
    - 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
mybatis:
  configuration:
     map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hl.myblog.po
#FastDfs的配置
StorageIP: 172.17.0.1:8888
fdfs:
   connect-timeout: 1000            #读取inputsream阻塞时间 
   so-timeout: 3000
   trackerList: 172.17.0.1:22122 #tracker地址
   thumb-image:                     #缩略图生成参数
      width: 150
      height: 150
   web-server-url: http://${StorageIP}/
logging:
      pattern:
        console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(-){faint} %clr([%14.14t]){faint} %clr(%-40.40logger.%13.13M){cyan} %clr(%3.3L) %clr(:){faint} %msg%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
      level:
        root: info
        com.hl.myblog: debug
        com.hl.myblog.dao: debug
      file:
        name: log/myblog-dev.log